### ISSUE TITLE
Option values with quotes are not properly processed

### ISSUE THREAD

**Issue by Imagine-Programming** [jamolnng/argparse#1]
When for example invoking a program using argparse with the following format:

somecommand --action "C:\Users\User Name\Directory - Name\file.dat" 

argparse will process the value as "C:\Users\User Name\Directory ". I assume that this is happening because of the dash in the path, argparse is considering the characters following that a new option. Quotes are ignored in that respect, as the dash should not be processed inside of a string parameter.

**Comment by jamolnng** [comment]
fixed in: https://github.com/jamolnng/argparse/commit/ff327e98e841e229e37a700287912742d7a45ae7

ran the (new) example like this and it appears to work correctly
`./example "0 -c" abc -a 1 -sdfl --flag -v 1 2.7 3 4 9 8.12 87 -o "C:\Users\User Name\Directory - Name\file.dat" "C:\Users\User Name 2\Directory 2 - Name 2\file2.dat" C:/tmp/tmp.dat`
