### ISSUE TITLE
Poisitional argument expected in position 1, but argument -v found instead

### ISSUE THREAD

**Issue by DeltaHosted** [jamolnng/argparse#11]
After going through all the process specified in the README.md file, I have tried to run the "examples" file in the build folder. However, instead of getting the expected output ("an even more verbose string\n a verbose string\n some verbosity") I have gotten the following error log:

> ./examples -v 2
Poisitional argument expected in position 1, but argument -v found instead

**Comment by jamolnng** [comment]
The example has the line

```cpp
parser.add_argument("-d", "--dtest", "dtest", true).position(0);
```

So it expects something to be in that first argument, so what you have causes an error but this wouldn't

`./examples "something" -v 2 "something else"`

The "something else" is there because it expects a last argument, otherwise it would see '2' as the last argument

example of what I mean:

```
> ./examples "something" -v 2
some verbosity
2
something

> ./examples "something" -v 2 "something else"
an even more verbose string
a verbose string
some verbosity
something else
something
```

**Comment by jamolnng** [comment]
I guess I need to update the readme

**Comment by jamolnng** [comment]
updated the readme to reflect the new example code https://github.com/jamolnng/argparse/commit/ac63b7a6a7c584539494430de36716b97a8f01d4
